### ISSUE TITLE
Support column names right after table name in the InsertStatement

### ISSUE THREAD

**Issue by NikitaShkaruba** [gravity-ui/sql-autocomplete-parsers#28]
Currently this query shows up an error `INSERT INTO cars(id, name, model, is_electrical) VALUES(43, 'oka', '123', true);` because `(id, name, model, is_electrical)` is not supported.

We need to support this syntax (so that there's no error highlighting), and also start suggesting column names in a query like this `INSERT INTO cars(|` or `INSERT INTO cars(id, |`

**Comment by viladimiru** [comment]
Currently our solution didn't support `INSERT INTO` template
